version: "3.6"
services:
  nats:
    image: nats:alpine
    network_mode: host
#    ports:
#      - "4222:4222"
#      - "8222:8222"
  def-job:
    image: golang:alpine
    volumes:
      - .:/job
    working_dir: /job
    command: go run job/job.go
    network_mode: host
  cron-job:
    image: golang:alpine
    volumes:
      - .:/cronjob
    working_dir: /cronjob
    command: go run cronjob/cronjob.go
    network_mode: host