version: "3.6"
services:
  pg_db:
    image: postgres:13
    #    restart: always
    environment:
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host
  nats:
    image: nats:alpine
    network_mode: host
    ports:
      - "4222:4222"
      - "8222:8222"
  def-job:
    build:
      context: ./
      dockerfile: job.Dockerfile
    container_name: def-job
    network_mode: host
  cron-job:
    build:
      context: ./
      dockerfile: cronJob.Dockerfile
    container_name: cron-job
    network_mode: host
