version: "3.6"
services:
  nats:
    image: nats:alpine
    network_mode: host
    ports:
      - "4222:4222"
      - "8222:8222"
  def-job:
    build:
      context: ./
      dockerfile: job.Dockerfile
    network_mode: host
  cron-job:
    build:
      context: ./
      dockerfile: cronJob.Dockerfile
    network_mode: host
