version: "3.6"
services:
#  nats:
#    image: nats:alpine
#    container_name: nats_core
#    network_mode: host
#    command: [ "-VV"]
#    ports:
#      - "4222:4222"
#      - "8222:8222"
  nats-streaming:
    image: nats-streaming:alpine
    command: --store FILE --dir datastore -cid cluster1 -m 8222
#    depends_on:
#      - nats
    network_mode: host
  def-job:
    image: golang:alpine
    volumes:
      - .:/job
    working_dir: /job
    command: go run job/job.go
    network_mode: host
  cron-job:
    image: golang:alpine
    volumes:
      - .:/cronjob
    working_dir: /cronjob
    command: go run cronjob/cronjob.go
    network_mode: host