version: "3.6"
services:
  pg_db:
    image: postgres:13
    #    restart: always
    environment:
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host